Metrics/LineLength:
  Max: 122

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/PredicateName:
  Exclude:
    - 'lib/filter_factory/condition.rb'
    - 'lib/filter_factory/active_record/condition.rb'
    - 'lib/filter_factory/mongoid/condition.rb'
